name: Release Caddy binary (xcaddy)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write 

jobs:
  build:
    name: Build caddy (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:   [ linux ]
        goarch: [ amd64, arm64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy with module
        env:
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: '0'
        run: |
          echo "Building for ${GOOS}-${GOARCH} using tag ${{ github.ref_name }}"
          xcaddy build \
            --with github.com/Bl4cky99/caddy-redirector=.

          out="caddy-${GOOS}-${GOARCH}"
          mv caddy "${out}"
          tar -czf "${out}.tar.gz" "${out}"
          shasum -a 256 "${out}.tar.gz" > "${out}.tar.gz.sha256"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: caddy-binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
            caddy-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256

  release:
    name: Publish GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/**/caddy-*.tar.gz
            dist/**/caddy-*.tar.gz.sha256
